@startuml
!include <C4/C4_Context.puml>

title Code Diagram for API Controller

Component_Boundary(api, "API") {
    Component(controller, "Controller", "Spring MVC") {
        [LoginHandler]
        [UserService]
    }
    Component(service, "Service", "Spring Bean") {
        [UserManager]
    }
}

[LoginHandler] --> [UserService]
[UserService] --> [UserManager]

SHOW_LEGEND()
@enduml