
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml

title Code Diagram for Banking System

namespace banking.controllers {
    class AccountController {
        + createAccount(AccountDTO): Account
        + getBalance(accountId): BigDecimal
        + transfer(TransferDTO): boolean
    }

    class TransactionController {
        + processTransaction(TransactionDTO): Transaction
        + getTransactionHistory(accountId): List<Transaction>
    }
}

namespace banking.services {
    interface AccountService {
        + createAccount(AccountDTO): Account
        + getBalance(accountId): BigDecimal
        + transfer(accountId, amount): boolean
    }

    class AccountServiceImpl {
        - accountRepository: AccountRepository
        + createAccount(AccountDTO): Account
        + getBalance(accountId): BigDecimal
        + transfer(accountId, amount): boolean
    }
}

namespace banking.repositories {
    interface AccountRepository {
        + save(Account): Account
        + findById(accountId): Optional<Account>
        + updateBalance(accountId, amount): void
    }
}

namespace banking.models {
    class Account {
        - id: UUID
        - balance: BigDecimal
        - owner: String
        - type: AccountType
    }

    enum AccountType {
        SAVINGS
        CHECKING
        INVESTMENT
    }
}

banking.controllers.AccountController --> banking.services.AccountService
banking.services.AccountServiceImpl ..|> banking.services.AccountService
banking.services.AccountServiceImpl --> banking.repositories.AccountRepository
banking.repositories.AccountRepository --> banking.models.Account
banking.models.Account --> banking.models.AccountType

SHOW_LEGEND()
@enduml
